services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build: .
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/users_db"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres-data:
