name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérification du code source depuis GitHub
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Configuration Docker sur le runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à Docker Hub pour pousser l'image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker pour FastAPI
      - name: Build Docker image for FastAPI
        run: |
          docker-compose -f docker-compose.yml build

      # Pousser l'image Docker vers Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker-compose -f docker-compose.yml push
